# .github/dependabot.yml
# Dependabot v2 configuration for Bad-Idea-AI
version: 2

updates:
  # JavaScript / Node.js Dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    assignees:
      - "MrLightspeed"
    reviewers:
      - "MrLightspeed"
    labels:
      - "dependencies"
      - "npm"
      - "javascript"
    commit-message:
      prefix: "chore"
      prefix-development: "chore(dev)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    groups:
      # Development tools and linters
      dev-tools:
        patterns:
          - "prettier"
          - "husky"
          - "jsonlint*"
          - "*lint*"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      # Core production dependencies
      production-core:
        patterns:
          - "core-js"
          - "glob"
          - "minimatch"
          - "mkdirp"
        dependency-type: "production"
    # Version resolution strategy
    versioning-strategy: "increase"
    # Security updates should be prioritized
    insecure-external-code-execution: "allow"
    
  # Ruby / Bundler (Jekyll GitHub Pages)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    assignees:
      - "MrLightspeed"
    labels:
      - "dependencies"
      - "ruby"
      - "jekyll"
      - "github-pages"
    commit-message:
      prefix: "chore(jekyll)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: "increase-if-necessary"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    assignees:
      - "MrLightspeed"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"
      - "automation"
    commit-message:
      prefix: "ci"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
          
  # Smart Contract Dependencies (if Hardhat/Truffle config exists)
  - package-ecosystem: "npm"
    directory: "/contracts"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    assignees:
      - "MrLightspeed"
    reviewers:
      - "MrLightspeed"
    labels:
      - "dependencies"
      - "smart-contracts"
      - "security"
      - "high-priority"
      - "requires-audit"
    commit-message:
      prefix: "fix(contracts)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    # Very conservative for contract dependencies
    versioning-strategy: "increase-if-necessary"
    allow:
      - dependency-type: "all"
    # Critical security settings for smart contracts
    ignore:
      # Lock OpenZeppelin to v4.x until manual upgrade
      - dependency-name: "@openzeppelin/contracts"
        versions: ["5.x", "6.x"]
      - dependency-name: "*"
        update-types: ["version-update:semver-prerelease"]
      
